version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - Verbalinsurection
  ignore:
  - dependency-name: influx
    versions:
    - 5.7.0
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - Verbalinsurection
  ignore:
  - dependency-name: node
    versions:
    - 15.pre.slim
