version: '2'
services:
  covid-19:
    # depends_on:
    #  - influxdb
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_USER=${INFLUX_USER}
      - INFLUX_PASS=${INFLUX_PASS}
      # - SCHEDULE_H='1'
    links:
     - influxdb

  influxdb:
    image: influxdb:1.8.4
    # image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: covid19
      INFLUXDB_ADMIN_ENABLED: 'true'
      INFLUXDB_ADMIN_USER: ${INFLUX_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUX_PASS}
    volumes:
      - influxdb-storage:/var/lib/influxdb

  grafana:
    image: grafana/grafana:6.7.4
    # image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel,natel-influx-admin-panel,grafana-piechart-panel
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
      - ./Dashboards/Corona.json:/var/lib/grafana/dashboards/Corona.json
      - ./Dashboards/COVID-19 per Country.json:/var/lib/grafana/dashboards/COVID-19 per Country.json
    # depends_on:
    #   - influxdb
    links:
      - influxdb

volumes:
  influxdb-storage:
  grafana-storage:
